
export enum TxType { DEPOSIT='DEPOSIT', WITHDRAWAL='WITHDRAWAL', TRANSFER='TRANSFER', TRADE='TRADE', COMMISSION='COMMISSION' }
export enum OrderSide { BUY='BUY', SELL='SELL' }
export enum OrderType { LIMIT='LIMIT', MARKET='MARKET' }
export enum OrderStatus { NEW='NEW', FILLED='FILLED', PARTIAL='PARTIAL', CANCELED='CANCELED' }
